# Creates multiple Drupal web apps sharing the same MySQL database
# Usage: docker-compose up -d
version: '2'
services:
  drupal:
    build:
      context: ./builds/drupal-apache
    image: drupal:8.2.3-apache
    volumes:
      - /var/www/html
      - ./scripts/php.ini:/usr/local/etc/php/php.ini
      - ./scripts/settings.php:/var/www/html/sites/default/settings.php
      - ./scripts:/scripts
      #- ./modules/:/var/www/html/modules
      #- ./themes/:/var/www/html/themes
      #- ./libraries/:/var/www/html/libraries
      #- ./profiles/:/var/www/html/profiles
      #- $(which drush):/usr/local/bin/drush
      #- $(which drupal):/usr/local/bin/drupal
    volumes_from:
      - mysql
    ports:
      - "8082:80"
    links:
      - mysql
      - phpmyadmin
    container_name: drupal_8082
  drupal_slave:
    image: drupal:8.2.3-apache
    volumes_from:
      - drupal
      - mysql
    ports:
      - "80"
    links:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: localhost
    volumes:
      - /var/lib/mysql
      - /usr/bin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_8090
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '8090:80'
    links:
      - mysql
